baseurl = "https://bonobo.games/"
languageCode = 'en-us'
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "BONOBO GAMES"
canonifyurls  = true
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
ignoreLogs = ['warning-goldmark-raw-html']
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  since        = "2024"
  subtitle     = "Play nice. Make games."
  comments     = false

  # Header image for the main page
  bigimg = [
    { src = "/header.jpg" }
  ]

[Params.Author]
  name    = "BONOBO GAMES"
  email   = "gsm@bonobo.games"
  github  = "BONOBOGAMES"
  twitter = "bonobogames_hun"
  reddit  = "GSM_BONOBO"

[[menu.main]]
  name   = "Games"
  url    = "/games/"
  weight = 1

[[menu.main]]
  name   = "Team"
  url    = "/team/"
  weight = 2

